// Generated by Selenium IDE

//Test Script to create the Customer, after creation of customer user will be added for that account

package dfm;

import org.junit.Test;
import org.junit.Before;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.Duration;
import java.util.*;

public class AddCustomer {
	public WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();

//		System.setProperty("webdriver.edge.driver", "./Driver/msedgedriver.exe");
//		driver=new EdgeDriver();
	}

	@After
	public void tearDown() {
		// driver.quit();
	}

	@Test
	public void tC04() throws InterruptedException, IOException, Exception {

		// For QA environment
		// driver.get("https://qa.admin.decisionsfirst.com/login");

		// For Openshift
		driver.get("https://admin-dfm-dms.apps.oc-prod.decisionsfirst.com");

		driver.manage().window().maximize();
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("dmsadmin@dmsadmin.com");
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("dms@123");
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(8000);

		{
			WebElement element = driver.findElement(By.cssSelector(".btn"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		driver.findElement(By.cssSelector(".add-customer-link > .item-text")).click();
		driver.findElement(By.cssSelector("p")).click();

		// Get the Customer data form Excel Sheet
		File src = new File("./Test Data/TestData.xlsx");
		FileInputStream fis = new FileInputStream(src);
		XSSFWorkbook workbook = new XSSFWorkbook(fis);

		XSSFSheet sheet = workbook.getSheet("AddCustomer");

		String customerName = sheet.getRow(1).getCell(0).getStringCellValue();

		DataFormatter dataFormatter = new DataFormatter();

		// Input data from excel for number of Users
		String numberOfUsersValue = dataFormatter.formatCellValue(sheet.getRow(1).getCell(1));
		String domains = sheet.getRow(1).getCell(2).getStringCellValue();

		driver.findElement(By.xpath("//div[@class='ql-editor ql-blank']")).sendKeys(customerName);

		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("numberOfUsers")).click();
		driver.findElement(By.id("numberOfUsers")).clear();
		driver.findElement(By.id("numberOfUsers")).sendKeys(numberOfUsersValue);
		driver.findElement(By.id("domains")).click();
		driver.findElement(By.id("domains")).sendKeys(domains);
		driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
		Thread.sleep(5000);

		driver.findElement(By.cssSelector(".form-control")).click();
		driver.findElement(By.xpath("//input[@placeholder='Search']")).sendKeys("Test dummy");
		Thread.sleep(4000);
		driver.findElement(By.cssSelector("span > .item-name")).click();

		Thread.sleep(2000);

		// Get all the User1 data from Excel Sheet
		String firstNameUser1 = sheet.getRow(1).getCell(4).getStringCellValue();
		String lastNameUser1 = sheet.getRow(2).getCell(4).getStringCellValue();
		String customerEmailUser1 = sheet.getRow(3).getCell(4).getStringCellValue();
		String customerTypeUser1 = sheet.getRow(4).getCell(4).getStringCellValue();

		driver.findElement(By.cssSelector(".add-user-button")).click();
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'firstName\']/quill-editor/div[2]/div/p"))
				.sendKeys(firstNameUser1);
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'lastName\']/quill-editor/div[2]/div/p"))
				.sendKeys(lastNameUser1);
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'email\']/quill-editor/div[2]/div/p"))
				.sendKeys(customerEmailUser1);
		driver.findElement(By.cssSelector(".ng-touched > .form-control")).click();
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".ng-touched > .form-control"));
			dropdown.findElement(By.xpath(customerTypeUser1)).click();
		}
		driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
		driver.findElement(By.xpath("//button[@type='button'][normalize-space()='Add User']")).click();

		Thread.sleep(5000);
		// Get all the User1 data from Excel Sheet
		String firstNameUser2 = sheet.getRow(1).getCell(5).getStringCellValue();
		String lastNameUser2 = sheet.getRow(2).getCell(5).getStringCellValue();
		String customerEmailUser2 = sheet.getRow(3).getCell(5).getStringCellValue();
		String customerTypeUser2 = sheet.getRow(4).getCell(5).getStringCellValue();

		driver.findElement(By.cssSelector(".add-user-button")).click();
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'firstName\']/quill-editor/div[2]/div/p"))
				.sendKeys(firstNameUser2);
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'lastName\']/quill-editor/div[2]/div/p"))
				.sendKeys(lastNameUser2);
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'email\']/quill-editor/div[2]/div/p"))
				.sendKeys(customerEmailUser2);
		driver.findElement(By.cssSelector(".ng-touched > .form-control")).click();
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".ng-touched > .form-control"));
			dropdown.findElement(By.xpath(customerTypeUser2)).click();
		}
		driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
		driver.findElement(By.xpath("//button[@type='button'][normalize-space()='Add User']")).click();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(5000);

		//Find element by xpath and store in variable "Element"        		
        //WebElement Element = driver.findElement(By.xpath("//button[normalize-space()='Add Group']"));

        //This will scroll the page till the element is found		
        //js.executeScript("arguments[0].scrollIntoView();", Element);
		
		// js.executeScript("window.scrollTo(1000, document.body.scrollHeight)");
		
//		JavascriptExecutor js = (JavascriptExecutor) driver;
//		js.executeScript("window.scrollBy(0,1000)");
		
		
		Robot robot = new Robot();
		robot.keyPress(KeyEvent.VK_CONTROL);
		robot.keyPress(KeyEvent.VK_END);
		robot.keyRelease(KeyEvent.VK_END);
		robot.keyRelease(KeyEvent.VK_CONTROL);

		System.out.println("<<<<Customer added successfully>>>>");
		workbook.close();

	}
}
