// Generated by Selenium IDE

package dfm;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class AddCust {
	public WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();
	}

	@After
	public void tearDown() {
		// driver.quit();
	}

	@Test
	public void tC04() throws InterruptedException {
		driver.get("https://qa.admin.decisionsfirst.com/login");
		// driver.manage().window().setSize(new Dimension(698, 602));
		driver.manage().window().maximize();
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("dmsadmin@dmsadmin.com");
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("dms@123");
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(8000);

		{
			WebElement element = driver.findElement(By.cssSelector(".btn"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		driver.findElement(By.cssSelector(".add-customer-link > .item-text")).click();
		driver.findElement(By.cssSelector("p")).click();

//		{
//			WebElement element = driver.findElement(By.xpath("//input[@type='text']"));
//			js.executeScript(
//					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test Dummy</p>'}",
//					element);
//		}
		driver.findElement(By.xpath("//div[@class='ql-editor ql-blank']")).sendKeys("Test dummy");

		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("numberOfUsers")).click();
		driver.findElement(By.id("numberOfUsers")).clear();
		driver.findElement(By.id("numberOfUsers")).sendKeys("10");
		driver.findElement(By.id("domains")).click();
		driver.findElement(By.id("domains")).sendKeys("dummy.com");
		driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
		Thread.sleep(4000);

		driver.findElement(By.cssSelector(".form-control")).click();
		driver.findElement(By.xpath("//input[@placeholder='Search']")).sendKeys("test dummy");
		Thread.sleep(2000);
		driver.findElement(By.cssSelector("span > .item-name")).click();

		Thread.sleep(2000);
		driver.findElement(By.cssSelector(".add-user-button")).click();
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'firstName\']/quill-editor/div[2]/div/p"))
				.sendKeys("Admin");
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'lastName\']/quill-editor/div[2]/div/p"))
				.sendKeys("Tester");
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'email\']/quill-editor/div[2]/div/p"))
				.sendKeys("Admin@dummy.com");
		driver.findElement(By.cssSelector(".ng-touched > .form-control")).click();
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".ng-touched > .form-control"));
			dropdown.findElement(By.xpath("//option[. = 'ADMIN']")).click();
		}
		driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
		driver.findElement(By.xpath("//button[@type='button'][normalize-space()='Add User']")).click();

		Thread.sleep(6000);
		driver.findElement(By.cssSelector(".add-user-button")).click();
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'firstName\']/quill-editor/div[2]/div/p"))
				.sendKeys("Standard");
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'lastName\']/quill-editor/div[2]/div/p"))
				.sendKeys("Tester");
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'email\']/quill-editor/div[2]/div/p"))
				.sendKeys("Standard@dummy.com");
		driver.findElement(By.cssSelector(".ng-touched > .form-control")).click();
		{
			WebElement dropdown = driver.findElement(By.cssSelector(".ng-touched > .form-control"));
			dropdown.findElement(By.xpath("//option[. = 'STANDARD']")).click();
		}
		driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
		driver.findElement(By.xpath("//button[@type='button'][normalize-space()='Add User']")).click();
	}
}
