// Generated by Selenium IDE

package dfm;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;
public class AddGroupsModelerUI01Test {
  private static WebDriver driver;
  //private Map<String, Object> vars;
  JavascriptExecutor js;
  
  public static void main(String[] args) throws InterruptedException {
	setUp();
	addGroupsModelerUI01();
}
  
  //@Before
  public static void setUp() {
	  System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();
  }
  //@After
  public void tearDown() {
    driver.quit();
  }
  //@Test
  public static void addGroupsModelerUI01() throws InterruptedException {
    // Test name: AddGroupsModelerUI_01
    // Step # | name | target | value
    // 1 | open | https://qa.modeler2.decisionsfirst.com/login | 
    driver.get("https://qa.modeler2.decisionsfirst.com/login");
    // 2 | setWindowSize | 1936x1048 | 
    driver.manage().window().maximize();
    // 3 | click | css=.form-group:nth-child(2) > .form-control | 
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
    // 4 | type | xpath=//input[@type='text'] | nitesh@rxw.com
    driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("nitesh@rxw.com");
    // 5 | click | css=.ng-untouched | 
    driver.findElement(By.cssSelector(".ng-untouched")).click();
    // 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
    // 7 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    
Thread.sleep(8000);
    
    {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
      }
    
    // 8 | click | css=.sidebar-control-button | 
    driver.findElement(By.cssSelector(".sidebar-control-button")).click();
    // 9 | click | css=.item:nth-child(10) > .item-text | 
    driver.findElement(By.cssSelector(".item:nth-child(10) > .item-text")).click();
    // 10 | click | css=.nav-link-group > .tab-text-container | 
    Thread.sleep(4000);
    driver.findElement(By.cssSelector(".nav-link-group > .tab-text-container")).click();
    // 11 | click | css=.title-icon > .eva | 
    driver.findElement(By.cssSelector(".title-icon > .eva")).click();
    // 12 | click | css=.rich-text-editor-focus p |
    Thread.sleep(2000);
   // driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
    
    // 13 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>Test Group</p>
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test Group</p>'}", element);
//    }
    Thread.sleep(2000);
    driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='name']//p")).sendKeys("Test 1");
    
    // 14 | click | css=.ql-blank > p | 
    driver.findElement(By.cssSelector(".ql-blank > p")).click();
    // 15 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>test</p>
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test</p>'}", element);
//    }
    
    driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='description']//p")).sendKeys("test group");
    
    // 16 | click | css=.group-item:nth-child(1) > div | 
   // driver.findElement(By.cssSelector(".group-item:nth-child(1) > div")).click();
    // 17 | click | css=div:nth-child(3) > .btn | 
   // driver.findElement(By.cssSelector("div:nth-child(3) > .btn")).click();
    // 18 | mouseOver | css=div:nth-child(3) > .btn | 
    
//    {
//      WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .btn"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
    
    
    // 19 | mouseOut | css=.nb-spinner-container | 
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
    
    driver.findElement(By.xpath("//td[@class='fieldData']//label[1]")).click();
    
    // 20 | click | css=div:nth-child(3) > .btn | 
   // driver.findElement(By.cssSelector("div:nth-child(3) > .btn")).click();
    // 21 | click | css=.rich-text-editor-focus p | 
   // driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
    // 22 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>Test Group1</p>
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test Group1</p>'}", element);
//    }
    // 23 | click | css=div:nth-child(3) > .btn | 
   // driver.findElement(By.cssSelector("div:nth-child(3) > .btn")).click();
    driver.findElement(By.xpath("//button[normalize-space()='Add Group']")).click();
    
    System.out.println("<<<<<Groups added Successfully>>>>>");
    
  }
}
