// Generated by Selenium IDE

//Script to Create Group

package dfm;

import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.dfm.utility.Helper;

import org.openqa.selenium.JavascriptExecutor;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.time.Duration;

public class AddGroupsModelerUI01Test {
	private static WebDriver driver;
	// private Map<String, Object> vars;
	JavascriptExecutor js;
	
	ExtentSparkReporter sparkReporter;
	public static ExtentReports reports;
	static ExtentTest extentTest;

	Reporter report = new Reporter();
	
	@BeforeSuite(alwaysRun = true)
	public void setUpReport() {

		
		sparkReporter = new ExtentSparkReporter(new File(
				System.getProperty("user.dir") + "./Reports/Groups/DFM_AddGroup_" + Helper.getCurrentDateTime() + ".html"));
		reports = new ExtentReports();
		reports.attachReporter(sparkReporter);

	}

	@BeforeClass
	public static void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();

		// System.setProperty("webdriver.edge.driver", "./Driver/msedgedriver.exe");
		// driver=new EdgeDriver();
	}

	@AfterClass
	public void tearDown() {
		// driver.quit();
	}

	@Test(priority = 1)
	public static void loginAction() throws InterruptedException, IOException {
		
		// reports.createTest("Login");
				Reporter.log("Test Case for Add Group");
				extentTest = reports.createTest("Login", "Login to DFM Application");
				// log with snapshot
//				extentTest.pass("Details",
//						MediaEntityBuilder.createScreenCaptureFromPath("./Screenshots/screenshot.png").build());
				// test with snapshot
				extentTest.addScreenCaptureFromPath("screenshot.png");

				// log(Status, details)
				extentTest.log(Status.INFO, "Starting Test Case");

		// For QA Environment
		// 1 | open | https://qa.modeler2.decisionsfirst.com/login |
		driver.get("https://qa.modeler2.decisionsfirst.com/login");
		extentTest.pass("Navigates to DFM URL");

		// For Openshift Environment
		// driver.get("https://modeler2-dfm-dms.apps.oc-prod.decisionsfirst.com/login");

		// 2 | setWindowSize | 1936x1048 |
		driver.manage().window().maximize();
		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | xpath=//input[@type='text'] | nitesh@rxw.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("nitesh@rxw.com");
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		extentTest.pass("Login Sucessfull");

		Thread.sleep(15000);

		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}

		/*
		 * WebElement close_option_tab =
		 * driver.findElement(By.xpath("//button[normalize-space()='CLOSE']")); if
		 * (close_option_tab.isDisplayed()) { close_option_tab.click();
		 * 
		 * } else {
		 * System.out.println("Wijmo Evaluation Version (5.20213.824) is not available"
		 * );
		 * 
		 * }
		 */

		// 8 | click | css=.sidebar-control-button |
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		// 9 | click | css=.item:nth-child(10) > .item-text |
		driver.findElement(By.cssSelector(".item:nth-child(10) > .item-text")).click();
		// 10 | click | css=.nav-link-group > .tab-text-container |
		Thread.sleep(4000);
	}

	@Test(priority = 2)
	public static void addGroups() throws InterruptedException, IOException {
		driver.findElement(By.xpath("//div[contains(text(),'Groups')]")).click();
		extentTest.pass("Clicked on Groups Tab");
		// 11 | click | css=.title-icon > .eva |
		//driver.findElement(By.cssSelector(".title-icon > .eva")).click();
		driver.findElement(By.xpath("//div[@class='title-icon']//i[@class='eva eva-plus-circle-outline']")).click();
		// 12 | click | css=.rich-text-editor-focus p |
		Thread.sleep(2000);

		File src = new File("./Test Data/TestData.xlsx");
		FileInputStream fis = new FileInputStream(src);
		XSSFWorkbook workbook = new XSSFWorkbook(fis);

		XSSFSheet sheet = workbook.getSheet("AddGroupsModelerUI01Test");

		// Get the data of Add Group form Excel Sheet
		String groupName = sheet.getRow(1).getCell(0).getStringCellValue();
		String description = sheet.getRow(1).getCell(1).getStringCellValue();
		String permissions = sheet.getRow(1).getCell(2).getStringCellValue();

		// Thread.sleep(2000);
		// Enter Group Name
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='name']//p")).sendKeys(groupName);
		extentTest.pass("Entered Group Name");

		// 14 | click | css=.ql-blank > p |
		driver.findElement(By.cssSelector(".ql-blank > p")).click();

		// Enter Description
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='description']//p")).sendKeys(description);
		extentTest.pass("Entered Group Description");

		// Thread.sleep(2000);
		WebElement fieldData = driver.findElement(By.xpath(permissions));
		fieldData.click();
		extentTest.pass("Selected Group Permission");
		// driver.findElement(By.xpath("//td[@class='fieldData']//label[1]")).click();

		// 23 | click | css=div:nth-child(3) > .btn |
		// driver.findElement(By.cssSelector("div:nth-child(3) > .btn")).click();
		driver.findElement(By.xpath("//button[normalize-space()='Add Group']")).click();
		extentTest.pass("Clicked on Add Group button");

		System.out.println("<<<<<Groups added Successfully>>>>>");
		workbook.close();
	}
	
	@Test(priority = 3)
	public static void ValidateGroups() throws InterruptedException, IOException {
		
		Thread.sleep(4000);
		addGroups();
		
		extentTest.pass("Validated Group Name");

		extentTest.log(Status.INFO, "Test Completed");
	}
	
	@AfterSuite(alwaysRun = true)
	public void tearDownReport() {

		// calling flush writes everything to the log file
		reports.flush();
	}
}
