// Generated by Selenium IDE

//Script to add group with different permission, Fetch the xpath according to the Permissions from the Excel Sheet while Adding Group

package dfm;

import org.junit.Test;
import org.junit.Before;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.Duration;
import java.util.*;

public class AddGroupsModelerUIWithDifferentPermission {
	private static WebDriver driver;
	// private Map<String, Object> vars;
	JavascriptExecutor js;

	public static void main(String[] args) throws Exception {
		setUp();
		addGroupsModelerUI01();
		// dataReadTest();
	}

	// @Before
	public static void setUp() {
//		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
//		driver = new ChromeDriver();

		System.setProperty("webdriver.edge.driver", "./Driver/msedgedriver.exe");
		driver = new EdgeDriver();
	}

	// @After
	public void tearDown() {
		// driver.quit();
	}

	// @Test
	public static void addGroupsModelerUI01() throws InterruptedException, IOException {

		File src = new File("./Test Data/TestData.xlsx");
		FileInputStream fis = new FileInputStream(src);
		XSSFWorkbook workbook = new XSSFWorkbook(fis);

		XSSFSheet sheet = workbook.getSheet("AddGroupsModelerUIWithDifferent");

		// Get the xpath of permissions form Excel Sheet
		String Permissions = sheet.getRow(1).getCell(1).getStringCellValue();
		String groupName = sheet.getRow(1).getCell(2).getStringCellValue();
		String description = sheet.getRow(1).getCell(3).getStringCellValue();

		// Test name: AddGroupsModelerUI_01
		// Step # | name | target | value

		// For QA Environment
		// 1 | open | https://qa.modeler2.decisionsfirst.com/login |
		driver.get("https://qa.modeler2.decisionsfirst.com/login");

		// For Openshift Environment
		driver.get("https://modeler2-dfm-dms.apps.oc-prod.decisionsfirst.com/login");

		// 2 | setWindowSize | 1936x1048 |
		driver.manage().window().maximize();
		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | xpath=//input[@type='text'] | nitesh@rxw.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("Admin@dummy.com");
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();

		Thread.sleep(8000);

		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}

		WebElement close_option_tab = driver.findElement(By.xpath("//button[normalize-space()='CLOSE']"));
		if (close_option_tab.isDisplayed()) {
			close_option_tab.click();

		} else {
			System.out.println("Wijmo Evaluation Version (5.20213.824) is not available");

		}

		// 8 | click | css=.sidebar-control-button |
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		// 9 | click | css=.item:nth-child(10) > .item-text |
		driver.findElement(By.cssSelector(".item:nth-child(10) > .item-text")).click();
		// 10 | click | css=.nav-link-group > .tab-text-container |
		Thread.sleep(2000);
		driver.findElement(By.cssSelector(".nav-link-group > .tab-text-container")).click();
		// 11 | click | css=.title-icon > .eva |
		driver.findElement(By.cssSelector(".title-icon > .eva")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='name']//p")).sendKeys(groupName);

		// 14 | click | css=.ql-blank > p |
		driver.findElement(By.cssSelector(".ql-blank > p")).click();

		// Enter description
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='description']//p")).sendKeys(description);

		// Select Permissions
		driver.findElement(By.xpath(Permissions)).click();

		driver.findElement(By.xpath("//button[normalize-space()='Add Group']")).click();

		System.out.println("<<<<<Groups with permission added Successfully>>>>>");

		workbook.close();

	}
}
