// Generated by Selenium IDE
package dfm;

import org.junit.Test;

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class AddProjectTagAndDiagram {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();
	}

	@After
	public void tearDown() {
		// driver.quit();
	}

	@Test
	public void addProject() throws InterruptedException {
		// Test name: Add Project
		// Step # | name | target | value
		// 1 | open | https://qa.modeler2.decisionsfirst.com/login |
		driver.get("https://qa.modeler2.decisionsfirst.com/login");
		// 2 | setWindowSize | 1126x602 |
		driver.manage().window().maximize();
		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | xpath=//input[@type='text'] | test_claim2@gmail.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("test_claim2@gmail.com");
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(15000);
		
		// 8 | waitForElementVisible | css=.sidebar-control-button | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}
		// 9 | click | css=.sidebar-control-button |
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		Thread.sleep(3000);
		// 10 | click | xpath=//span[contains(.,'Tag Explorer')] |
		driver.findElement(By.xpath("//span[contains(.,\'Tag Explorer\')]")).click();
		Thread.sleep(5000);
		// 11 | click | css=.eva-plus-circle-outline:nth-child(2) |
		driver.findElement(By.cssSelector(".eva-plus-circle-outline:nth-child(2)")).click();
		Thread.sleep(5000);
		// 12 | click | css=.wj-listbox-item:nth-child(1) > div |
		driver.findElement(By.cssSelector(".wj-listbox-item:nth-child(1) > div")).click();
		Thread.sleep(5000);
		// 13 | click | css=.rich-text-editor-focus p |
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='name']/quill-editor/div[2]/div/p"))
				.click();
		// Thread.sleep(5000);

		// 14 | editContent |
		// xpath=//core-edit-multiple-lines-control[@id='name']/quill-editor/div[2]/div
		// | <p>test dummy1</p>
//    {
//      WebElement element = driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'name\']/quill-editor/div[2]/div"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test dummy12</p>'}", element);
//    }

		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'name\']/quill-editor/div[2]/div"))
				.sendKeys("Test dummy 23");

		// 15 | click | css=.ql-blank > p |
		driver.findElement(By.cssSelector(".ql-blank > p")).click();

		// 16 | editContent |
		// xpath=//core-edit-multiple-lines-control[@id='description']/quill-editor/div[2]/div
		// | <p>test</p>
//    {
//      WebElement element = driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'description\']/quill-editor/div[2]/div"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test</p>'}", element);
//    }

		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id=\'description\']/quill-editor/div[2]/div"))
				.sendKeys("test");

		// 17 | click | xpath=//nb-radio[@id='item-enableSimpleBranching']/label/span[2]
		// |
		driver.findElement(By.xpath("//nb-radio[@id=\'item-enableSimpleBranching\']/label/span[2]")).click();
		// 18 | click | xpath=//button[contains(.,'Add Project')] |
		driver.findElement(By.xpath("//button[contains(.,\'Add Project\')]")).click();
		
		
		//Add Tag
		
		Thread.sleep(5000);
		// 10 | click | id=search-ip |
		driver.findElement(By.id("search-ip")).click();
		// 11 | type | id=search-ip | dummy
		driver.findElement(By.id("search-ip")).sendKeys("Test dummy 23");

		// identify element
		WebElement l = driver.findElement(By.xpath("//span[normalize-space()='Test dummy 23 (main)']"));
		// Actions class with moveToElement() and contextClick()
		Actions a = new Actions(driver);
		a.moveToElement(l).contextClick().build().perform();
		Thread.sleep(2000);

		// 13 | click | css=.rich-text-editor-focus p |
		driver.findElement(By.xpath("//div[contains(text(),'Add Tag')]")).click();

		// 14 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>test tag</p>
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test tag</p>'}", element);
//    }

		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='name']//div[@class='ql-editor ql-blank']"))
				.sendKeys("Test Tag");

		// 15 | click | css=.ql-blank > p |
//    driver.findElement(By.cssSelector(".ql-blank > p")).click();
		// 16 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>tag</p>
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>tag</p>'}", element);
//    }

		driver.findElement(
				By.xpath("//core-edit-multiple-lines-control[@id='description']//div[@class='ql-editor ql-blank']"))
				.sendKeys("Oct-22");

		// 17 | click | css=.btn-block |
		driver.findElement(By.xpath("//button[contains(.,'Add Tag')]")).click();
		Thread.sleep(5000);
		
		driver.findElement(By.xpath("//span[@class='wj-node-text has-text']")).click();
		
		
		// identify element
				WebElement tag = driver.findElement(By.xpath("//span[normalize-space()='Test Tag']"));
				// Actions class with moveToElement() and contextClick()
				Actions a1 = new Actions(driver);
				a1.moveToElement(tag).contextClick().build().perform();
				Thread.sleep(2000);
		driver.findElement(By.xpath("//div[contains(text(),'Create DRD')]")).click();
		Thread.sleep(2000);
		
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='diagramName']//p")).sendKeys("Test Diagram10");
		
		driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='diagramDescription']//p")).sendKeys("Oct-22");
		
		driver.findElement(By.xpath("//button[normalize-space()='Add Diagram']")).click();
		Thread.sleep(5000);
		
		driver.findElement(By.xpath("//i[@class='eva eva-settings-2-outline']")).click();
		Thread.sleep(12000);

		Actions act = new Actions(driver);

		WebElement src = driver.findElement(By.xpath(
				"//div[@class='add-object-palette']//canvas"));

		WebElement LINKS = driver.findElement(By.xpath(
				"//div[@class='links-palette']"));

		WebElement target = driver.findElement(By.xpath(
				"//div[@class='diagramDiv']//canvas"));

		// Knowledge Source data 1
//		act.moveToElement(src, 58, 5);
//		act.clickAndHold().moveByOffset(58, 5);
//		act.moveToElement(src, 250, 70);
//		act.moveToElement(target, 250, 70);
//		act.release();
//		act.perform();
//		Thread.sleep(4000);

		// Knowledge Source data 2

		// Decision data 1
//		act.moveToElement(src, -56, 5);
//		act.clickAndHold().moveByOffset(-56, 5);
//		act.moveToElement(src, 100, -50);
//		act.moveToElement(target, 100, -50);
//		act.release();
//		act.perform();
//		Thread.sleep(3000);

		// click Authority Links
//		act.moveToElement(LINKS, 10, 20);
//		act.click().build().perform();
//		Thread.sleep(2000);

		// creating the connection with links between Knowledge Source
//		act.moveToElement(target, 155, 75);
//		act.clickAndHold().moveByOffset(155, 75);
//		act.moveByOffset(105, -45);
//		act.release();
//		act.perform();
//		Thread.sleep(2000);

		// Knowledge Source data 1
		act.moveToElement(src, 15, 5);
		act.clickAndHold().moveByOffset(15, 5);
		act.moveToElement(src, 250, 70);
		act.moveToElement(target, 250, 70);
		act.release();
		act.perform();
		Thread.sleep(4000);

		// Decision Source data 1
		act.moveToElement(src, -56, 5);
		act.clickAndHold().moveByOffset(-56, 5);
		act.moveToElement(src, 150, 70);
		act.moveToElement(target, 150, 70);
		act.release();
		act.perform();
		Thread.sleep(3000);

		// Input Source data 1
		act.moveToElement(src, -30, 5);
		act.clickAndHold().moveByOffset(-30, 5);
		act.moveToElement(src, 300, -50);
		act.moveToElement(target, 300, -50);
		act.release();
		act.perform();
		Thread.sleep(3000);

		// click Authority Links
		act.moveToElement(LINKS, 10, 20);
		act.click().build().perform();
		Thread.sleep(2000);

		// creating the connection with links between Decision data 1 & Knowledge Source
		act.moveToElement(target, 155, 75);
		act.clickAndHold().moveByOffset(155, 75);
		act.moveByOffset(255, 65);
		act.release();
		act.perform();
		Thread.sleep(2000);

		// creating the connection with links between Input Source & Knowledge Source
		// data 1
		act.moveToElement(target, 180, -45);
		act.clickAndHold().moveByOffset(180, -45);
		act.moveByOffset(-100, 70);
		act.release();
		act.perform();
		Thread.sleep(2000);

		// click Information Links
		act.moveToElement(LINKS, -43, 20);
		act.click().build().perform();
		Thread.sleep(2000);

		// creating the connection with links between Input Source & Decision data 1
		act.moveToElement(target, 180, -45);
		act.clickAndHold().moveByOffset(180, -45);
		act.moveByOffset(-250, 70);
		act.release();
		act.perform();
		Thread.sleep(2000);

		// click Knowledge Source data 1
		act.moveToElement(target, 255, 75);
		act.click().build().perform();
		Thread.sleep(3000);

		// update Knowledge Source data 1
		driver.findElement(By.xpath("//*[@id='name']/quill-editor/div[2]/div[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id='name']/quill-editor/div[2]/div[1]"))
				.sendKeys("Knowledge name Updated");
		Thread.sleep(2000);

		// click Input Source data 1
		act.moveToElement(target, 305, -45);
		act.click().build().perform();
		Thread.sleep(3000);

		// update Input Source data 1
		driver.findElement(By.xpath("//*[@id='name']/quill-editor/div[2]/div[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id='name']/quill-editor/div[2]/div[1]"))
				.sendKeys("Input name Updated");
		Thread.sleep(2000);

		// click Decision Source data 1
		act.moveToElement(target, 155, 75);
		act.click().build().perform();
		Thread.sleep(3000);

		// update Decision Source data 1
		driver.findElement(By.xpath("//*[@id='name']/quill-editor/div[2]/div[1]")).clear();
		Thread.sleep(1000);
		driver.findElement(By.xpath("//*[@id='name']/quill-editor/div[2]/div[1]"))
				.sendKeys("Decision name Updated");
		Thread.sleep(2000);
		
		act.moveToElement(LINKS, -14, 120);
		act.contextClick().perform();

		System.out.println("<<<Diagram created>>>");
		
	}
}
