// Generated by Selenium IDE
package dfm;

import org.junit.Test;
import org.junit.Before;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.io.File;
import java.io.FileInputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class AddTagsToGroupTest {
	private static WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	public static void main(String[] args) throws Exception {
		setUp();
		addTagsToGroup();
	}

	// @Before
	public static void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();
	}

	// @After
	public void tearDown() {
		// driver.quit();
	}

	// @Test
	public static void addTagsToGroup() throws Exception {
		// Test name: AddTagsToGroup
		// Step # | name | target | value
		// 1 | open | https://qa.modeler2.decisionsfirst.com/login |
		driver.get("https://qa.modeler2.decisionsfirst.com/login");
		// 2 | setWindowSize | 1074x602 |
		driver.manage().window().maximize();
		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | css=.ng-valid | nitesh@rxw.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("nitesh@rxw.com");
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();

		Thread.sleep(15000);

		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}
		// 10 | click | css=.sidebar-control-button |
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		// 11 | click | css=.item:nth-child(10) > .item-text |
		driver.findElement(By.cssSelector(".item:nth-child(10) > .item-text")).click();
		// 12 | click | css=.nav-link-group > .tab-text-container |
		Thread.sleep(4000);
		driver.findElement(By.cssSelector(".nav-link-group > .tab-text-container")).click();
		Thread.sleep(3000);

		// Left click on the desired groups
//    WebElement l = driver.findElement(By.xpath("//div[contains(text(),'Test Group')]"));
//	Actions a = new Actions(driver);
//	a.moveToElement(l).contextClick().build().perform();

		// Get the xpath of tags of group form Excel Sheet
		File src = new File("./Test Data/TestData.xlsx");
		FileInputStream fis = new FileInputStream(src);
		XSSFWorkbook workbook = new XSSFWorkbook(fis);

		XSSFSheet sheet = workbook.getSheet("AddTagsToGroupTest");

		String editGroupXpath = sheet.getRow(1).getCell(0).getStringCellValue();
		String project = sheet.getRow(1).getCell(1).getStringCellValue();
		String branch = sheet.getRow(1).getCell(2).getStringCellValue();

		driver.findElement(By.xpath(editGroupXpath)).click();
		Thread.sleep(2000);

		// 15 | click | css=.tag-plus-icon > .eva |
		// driver.findElement(By.cssSelector(".tag-plus-icon > .eva")).click();
		driver.findElement(By.xpath("//div[@class='flex-grid-details']//div//i[@class='eva eva-plus-circle-outline']"))
				.click();
		Thread.sleep(2000);

		// 16 | click | css=.cdk-focused |
		// driver.findElement(By.cssSelector(".cdk-focused")).click();
		driver.findElement(By.xpath("//span[@class='tag-plus-icon']//i[@class='eva eva-plus-circle-outline']")).click();
		Thread.sleep(2000);

		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Select Project']")).click();
		{
			WebElement dropdown = driver.findElement(By.xpath("//button[normalize-space()='Select Project']"));
			dropdown.findElement(By.xpath(project)).click();
		}

		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[normalize-space()='Select Branch']")).click();
		{
			WebElement dropdown = driver.findElement(By.xpath("//button[normalize-space()='Select Branch']"));
			dropdown.findElement(By.xpath(branch)).click();
		}

		Thread.sleep(2000);
		// 26 | click | css=div:nth-child(3) > .btn |
		driver.findElement(By.cssSelector("div:nth-child(3) > .btn")).click();

		System.out.println("<<<<<Tags added to group successfully>>>>>");
		workbook.close();
	}
}
