// Generated by Selenium IDE
package dfm;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.time.Duration;


public class AddUserModelerUI01Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
	driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    //driver.quit();
  }
  @Test
  public void addUserModelerUI01() throws InterruptedException {
    // Test name: AddUserModelerUI_01
    // Step # | name | target | value
    // 1 | open | https://qa.modeler2.decisionsfirst.com/login | 
    driver.get("https://qa.modeler2.decisionsfirst.com/login");
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
    // 2 | setWindowSize | 1289x602 | 
    driver.manage().window().maximize();
    // 3 | click | css=.form-group:nth-child(2) > .form-control | 
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
    // 4 | type | xpath=//input[@type='text'] | nitesh@rxw.com
    driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("nitesh@rxw.com");
    // 5 | click | css=.ng-untouched | 
    driver.findElement(By.cssSelector(".ng-untouched")).click();
    // 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
    driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
    // 7 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 8 | waitForElementVisible | css=.sidebar-control-button | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
    }
    // 9 | mouseOver | css=.btn | 
    {
      WebElement element = driver.findElement(By.cssSelector(".btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseOut | css=.btn | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | click | css=.sidebar-control-button | 
    driver.findElement(By.cssSelector(".sidebar-control-button")).click();
    // 12 | click | css=.item:nth-child(10) > .item-text | 
    driver.findElement(By.cssSelector(".item:nth-child(10) > .item-text")).click();
    // 13 | click | css=.plus-icon > .eva | 
    driver.findElement(By.cssSelector(".plus-icon > .eva")).click();
    Thread.sleep(3000);
    // 14 | click | css=.rich-text-editor-focus p | 
   // driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
    // 15 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>Test</p>
    
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Test</p>'}", element);
//    }
    
    driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='firstName']//p")).sendKeys("Test 5");
    
    
    // 16 | click | css=.rich-text-editor-focus p | 
    driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
    // 17 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>Standard</p>
    
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Standard</p>'}", element);
//    }
    
    driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='lastName']//p")).sendKeys("Standard 5");
    
    // 18 | click | css=.ql-blank > p | 
    driver.findElement(By.cssSelector(".ql-blank > p")).click();
    // 19 | editContent | css=.rich-text-editor-focus > .ql-editor | <p>test1@rxw.com</p>
    
//    {
//      WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>test1@rxw.com</p>'}", element);
//    }
    
    driver.findElement(By.xpath("//core-edit-multiple-lines-control[@id='email']//p")).sendKeys("test5@rxw.com");
    
    // 20 | click | css=.form-control:nth-child(2) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).click();
    // 21 | click | css=.btn-block | 
    driver.findElement(By.cssSelector(".btn-block")).click();
    System.out.println("<<<<<<<User created successfully>>>>>>>");
  }
  
}
