// Generated by Selenium IDE

//This script will add the User to the Group

package dfm;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.io.File;
import java.time.Duration;
import java.util.*;

public class AddUserToGroupModelerUI {
	private static WebDriver driver;
	private Map<String, Object> vars;
	static JavascriptExecutor js;

	// @Before
	public static void main(String[] args) throws InterruptedException {
		setUp();
		editUserModelerUI();
	}

	public static void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();
	}

	// @After
	public void tearDown() {
		// driver.quit();
	}
	

	// @Test
	public static void editUserModelerUI() throws InterruptedException {

		// Test name: EditUserModelerUI
		// Step # | name | target | value
		// 1 | open | https://qa.modeler2.decisionsfirst.com/login |
		driver.get("https://qa.modeler2.decisionsfirst.com/login");
		// 2 | setWindowSize | 1435x602 |
		driver.manage().window().maximize();
		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | xpath=//input[@type='text'] | nitesh@rxw.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("nitesh@rxw.com");
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(8000);

		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}
		// 8 | click | css=.sidebar-control-button |
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		// 9 | click | css=.item:nth-child(10) > .item-text |
		driver.findElement(By.cssSelector(".item:nth-child(10) > .item-text")).click();

		Thread.sleep(4000);
		WebElement l = driver.findElement(By.xpath("//div[contains(text(),'Test Undelete')]"));
		Actions a = new Actions(driver);
		a.moveToElement(l).contextClick().build().perform();

		Thread.sleep(2000);
		//Click on Edit User option
		driver.findElement(By.xpath("//div[contains(text(),'Edit User')]")).click();
		Thread.sleep(2000);

		// Select Group that need to add the user
		driver.findElement(By.xpath("//div[normalize-space()='Test Group']")).click();

		//Click on Save button
		driver.findElement(By.xpath("//button[normalize-space()='Save']")).click();
		Thread.sleep(2000);

		System.out.println("<<<<<User added to the group successfully>>>>>");
	}
}
