// Generated by Selenium IDE

package dfm;

import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.Duration;

public class ChangePasswordTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	FileInputStream fis;

	@BeforeClass
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@AfterClass
	public void tearDown() {
		// driver.quit();
	}

	@Test(priority = 1)
	public void logInAction() throws InterruptedException, IOException {

		File src = new File("./Test Data/TestData.xlsx");
		fis = new FileInputStream(src);
		XSSFWorkbook workbook = new XSSFWorkbook(fis);

		// Pass the same data present in AddCustomer sheet"
		XSSFSheet sheet = workbook.getSheet("ChangePassword");

		// Input data from excel for number of Users
		String userName = sheet.getRow(1).getCell(0).getStringCellValue();
		String userPassword = sheet.getRow(1).getCell(1).getStringCellValue();

		driver.get("https://qa.modeler2.decisionsfirst.com/login");

		// 2 | setWindowSize | 1126x602 |
		driver.manage().window().maximize();
		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | xpath=//input[@type='text'] | test_claim2@gmail.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys(userName);
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys(userPassword);
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(15000);

		// 8 | waitForElementVisible | css=.sidebar-control-button | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}
		
		workbook.close();
	}

	@Test(priority = 2)
	public void changePassword() throws InterruptedException, IOException {
		
		File src = new File("./Test Data/TestData.xlsx");
		fis = new FileInputStream(src);
		XSSFWorkbook workbook1 = new XSSFWorkbook(fis);

		// Pass the same data present in AddCustomer sheet"
		XSSFSheet sheet = workbook1.getSheet("ChangePassword");

		// Input data from excel for number of Users
		String userName = sheet.getRow(1).getCell(0).getStringCellValue();
		String userCurrentPassword = sheet.getRow(1).getCell(1).getStringCellValue();
		String userNewPassword = sheet.getRow(1).getCell(2).getStringCellValue();

		{
			WebElement element = driver.findElement(By.cssSelector(".btn"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		{
			WebElement element = driver.findElement(By.cssSelector("nb-list-item:nth-child(2) .eva"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		driver.findElement(By.cssSelector(".item:nth-child(12) > .item-text")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//button[normalize-space()='Change password']")).click();
		Thread.sleep(2000);
		// driver.findElement(By.cssSelector(".open-form-button")).click();
		// driver.findElement(By.cssSelector(".form-group:nth-child(1) >
		// .form-control")).click();
		driver.findElement(By.xpath("//input[@placeholder='Current password']")).sendKeys(userCurrentPassword);

		// driver.findElement(By.xpath("//input[@type='password']")).click();
		driver.findElement(By.xpath("//input[@placeholder='New password']")).sendKeys(userNewPassword);
		// driver.findElement(By.cssSelector(".ng-invalid:nth-child(1)")).click();
		driver.findElement(By.xpath("//input[@placeholder='Repeat New Password']")).sendKeys(userNewPassword);
		driver.findElement(By.cssSelector(".change-password-button")).click();
		Thread.sleep(6000);
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		driver.findElement(By.cssSelector(".logOut > .item-text")).click();
		Thread.sleep(6000);
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys(userName);
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys(userNewPassword);
		driver.findElement(By.cssSelector(".btn")).click();
		{
			WebElement element = driver.findElement(By.cssSelector(".btn"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		workbook1.close();
	}
	
}
