// Generated by Selenium IDE

//Test Script to add the user from Admin account
package dfm;

import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.dfm.utility.Helper;

import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.time.Duration;

public class DeleteUserModelerUI {
	private static WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	/*ExtentSparkReporter sparkReporter;
	ExtentReports reports;
	ExtentTest extentTest;
	Reporter report = new Reporter();*/

	@BeforeSuite
	public void setUpReport() {

		// start reporters
		/*sparkReporter = new ExtentSparkReporter(new File(System.getProperty("user.dir")
				+ "./Reports/Delete/DFM_DeleteUser" + Helper.getCurrentDateTime() + ".html"));
		reports = new ExtentReports();
		reports.attachReporter(sparkReporter);*/

	}

	@BeforeClass
	public static void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();

		// System.setProperty("webdriver.edge.driver", "./Driver/msedgedriver.exe");
		// driver=new EdgeDriver();
	}

	@AfterClass
	public void tearDown() throws InterruptedException {
		Thread.sleep(3000);
		driver.quit();
	}

	@AfterSuite
	public void tearDownReoport() {

		// calling flush writes everything to the log file
		//reports.flush();
	}

	@Test(priority = 0)
	public void loginAction() throws InterruptedException, IOException {

		//Reporter.log("Test Case for Delete User");
		//extentTest = reports.createTest("Delete User", "Login to DFM Application");

		// test with snapshot
		//extentTest.addScreenCaptureFromPath("screenshot.png");

		// log(Status, details)
		//extentTest.log(Status.INFO, "Starting Test Case");

		// For QA Environment
		// 1 | open | https://qa.modeler2.decisionsfirst.com/login |
		driver.get("https://qa.modeler2.decisionsfirst.com/login");

		// For Openshift Environment
		// driver.get("https://modeler2-dfm-dms.apps.oc-prod.decisionsfirst.com/login");

		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
		// 2 | setWindowSize | 1289x602 |
		driver.manage().window().maximize();

		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | xpath=//input[@type='text'] | nitesh@rxw.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("admin@random.com");
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		// 8 | waitForElementVisible | css=.sidebar-control-button | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}
	}

	@Test(priority = 1)
	public void navigateUserSection() throws InterruptedException, IOException {

//		WebElement close_option_tab = driver.findElement(By.xpath("//button[normalize-space()='CLOSE']"));
//		if (close_option_tab.isDisplayed()) {
//			close_option_tab.click();
//
//		} else {
//			System.out.println("Wijmo Evaluation Version (5.20213.824) is not available");
//
//		}

		Thread.sleep(4000);
		// 11 | click | css=.sidebar-control-button |
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		// 12 | click | css=.item:nth-child(10) > .item-text |
		driver.findElement(By.cssSelector(".item:nth-child(10) > .item-text")).click();
		
		Thread.sleep(3000);
	}

	@Test(priority = 2)
	public void deleteUserAndValidate() throws InterruptedException, IOException {

		File src = new File("./Test Data/TestData.xlsx");
		FileInputStream fis = new FileInputStream(src);
		XSSFWorkbook workbook = new XSSFWorkbook(fis);

		XSSFSheet sheet = workbook.getSheet("AddUserModelerUI01Test");

		// Get the xpath of delete user form Excel Sheet
		String deleteUser = sheet.getRow(1).getCell(5).getStringCellValue();
		String email = sheet.getRow(1).getCell(2).getStringCellValue();
		String password = sheet.getRow(1).getCell(4).getStringCellValue();

		// 21 | click | css=.btn-block |
		// driver.findElement(By.cssSelector(".btn-block")).click();
		Thread.sleep(5000);

		Actions actions = new Actions(driver);
		WebElement delete = driver.findElement(By.xpath(deleteUser));
		actions.contextClick(delete).build().perform();
		Thread.sleep(1000);

		driver.findElement(By.xpath("//div[normalize-space()='Delete User']")).click();
		 Thread.sleep(2000);
		 driver.findElement(By.xpath("//wj-popup[@class='wj-control wj-content wj-popup delete-confirmation-popup wj-state-focus wj-state-focused']//button[@class='btn btn-info popup-btn p-1'][normalize-space()='Delete']")).click();
		
		 {
				WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
				String Message =	wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@class='message']"))).getText();
				System.out.println("Success message after deletion of user : " + Message);
			}
		 Thread.sleep(5000);
		 
		// String message = driver.findElement(By.xpath("//div[@class='message']")).getText();
		//System.out.println("Sucess message after deletion of user : " + message);

		driver.findElement(By.xpath("//i[@class='sidebar-control-button nb-menu sidebar-toggle icon-gray-color']"))
				.click();
		// 11 | click | xpath=//span[contains(.,'Log Out')] |
		driver.findElement(By.xpath("//span[contains(.,\'Log Out\')]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys(email);
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys(password);
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(4000);

		String error_message = driver
				.findElement(By.xpath("//nb-alert[contains(text(),' You have entered an incorrect email address')]"))
				.getText();
		System.out.println("The message displayed after deletion of User is :  " + error_message);

//		if (driver.findElement(By.xpath("//nb-alert[contains(text(),' You have entered an incorrect email address')]")).isDisplayed()) {
//			
//			System.out.println("The User is deleted successfully");
//		} else {
//
//			System.out.println("The User is able to login successfully");
//		}
		//extentTest.log(Status.INFO, "Test Completed");

		workbook.close();
	}

}
