// Generated by Selenium IDE

//Test Script to create the Customer, after creation of customer user will be added for that account

package dfm;

import org.junit.Test;
import org.junit.Before;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.Duration;
import java.util.*;

public class DeleteCustomer {
	public static WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	public static void main(String[] args) throws InterruptedException, IOException, Exception {
		setUp();
		deleteCustomer();
	}

	// @Before
	public static void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();

//		System.setProperty("webdriver.edge.driver", "./Driver/msedgedriver.exe");
//		driver=new EdgeDriver();
	}

	// @After
	public void tearDown() {
		// driver.quit();
	}

	// @Test
	public static void deleteCustomer() throws InterruptedException, IOException, Exception {

		// For QA environment
		//driver.get("https://qa.admin.decisionsfirst.com/login");

		// For Openshift
		 driver.get("https://admin-dfm-dms.apps.oc-prod.decisionsfirst.com");

		driver.manage().window().maximize();
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("dmsadmin@dmsadmin.com");
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("dms@123");
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(8000);

		{
			WebElement element = driver.findElement(By.cssSelector(".btn"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		driver.findElement(By.cssSelector(".add-customer-link > .item-text")).click();
		driver.findElement(By.cssSelector("p")).click();

		// Get the Customer data form Excel Sheet
		File src = new File("./Test Data/TestData.xlsx");
		FileInputStream fis = new FileInputStream(src);
		XSSFWorkbook workbook = new XSSFWorkbook(fis);

		XSSFSheet sheet = workbook.getSheet("DeleteCustomer");

		String customerName = sheet.getRow(1).getCell(0).getStringCellValue();

		DataFormatter dataFormatter = new DataFormatter();

		// Input data from excel for number of Users
		String numberOfUsersValue = dataFormatter.formatCellValue(sheet.getRow(1).getCell(1));
		String domains = sheet.getRow(1).getCell(2).getStringCellValue();
		String customerDelete = sheet.getRow(1).getCell(0).getStringCellValue();

		driver.findElement(By.xpath("//div[@class='ql-editor ql-blank']")).sendKeys(customerName);

		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).clickAndHold().perform();
		}
		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.id("numberOfUsers"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).release().perform();
		}
		driver.findElement(By.id("numberOfUsers")).click();
		driver.findElement(By.id("numberOfUsers")).clear();
		driver.findElement(By.id("numberOfUsers")).sendKeys(numberOfUsersValue);
		driver.findElement(By.id("domains")).click();
		driver.findElement(By.id("domains")).sendKeys(domains);
		driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
		Thread.sleep(5000);

		driver.findElement(By.cssSelector(".form-control")).click();
		driver.findElement(By.xpath("//input[@placeholder='Search']")).sendKeys(customerDelete);
		Thread.sleep(4000);
		// driver.findElement(By.cssSelector("span > .item-name")).click();
		driver.findElement(By.xpath("//i[@class='eva eva-trash-2-outline remove-item icon-gray-color']")).click();
		Thread.sleep(5000);
		driver.findElement(By.xpath("//i[@class='btn btn-info eva eva-search-outline search-icon']")).click();

		System.out.println("<<<<Customer deleted successfully>>>>");
		workbook.close();

	}
}
