// Generated by Selenium IDE

package dfm;


import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.time.Duration;

public class KnowledgeSourceDataTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@BeforeClass
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "./Driver/chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@AfterClass
	public void tearDown() {
		//driver.quit();
	}

	public String waitForWindow(int timeout) {
		try {
			Thread.sleep(timeout);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		Set<String> whNow = driver.getWindowHandles();
		Set<String> whThen = (Set<String>) vars.get("window_handles");
		if (whNow.size() > whThen.size()) {
			whNow.removeAll(whThen);
		}
		return whNow.iterator().next();
	}

	@Test
	public void enterKnowledgeSourceDataDetails() throws InterruptedException {
		driver.get("https://qa.modeler2.decisionsfirst.com/login");

		// 2 | setWindowSize | 1126x602 |
		driver.manage().window().maximize();
		// 3 | click | css=.form-group:nth-child(2) > .form-control |
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
		// 4 | type | xpath=//input[@type='text'] | test_claim2@gmail.com
		driver.findElement(By.xpath("//input[@type=\'text\']")).sendKeys("nitesh@rxw.com");
		// 5 | click | css=.ng-untouched |
		driver.findElement(By.cssSelector(".ng-untouched")).click();
		// 6 | type | xpath=//input[@type='password'] | defaultUserPass@123
		driver.findElement(By.xpath("//input[@type=\'password\']")).sendKeys("defaultUserPass@123");
		// 7 | click | css=.btn |
		driver.findElement(By.cssSelector(".btn")).click();
		Thread.sleep(15000);

		// 8 | waitForElementVisible | css=.sidebar-control-button | 30000
		{
			WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(50));
			wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".sidebar-control-button")));
		}

		driver.findElement(By.cssSelector(".sidebar-control-button")).click();
		driver.findElement(By.cssSelector(".add-object-sidebar-panel > .item-text")).click();
		driver.findElement(By.id("addKnowledgeSource")).click();
		{
			WebElement element = driver
					.findElement(By.cssSelector("#knowledgeSourceDescription .ql-strike .ql-fill:nth-child(2)"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		{
			WebElement element = driver.findElement(By.cssSelector("#knowledgeSourceDescription .ql-underline > svg"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
//		driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
//		{
//			WebElement element = driver.findElement(By.cssSelector(".ng-pristine .ql-strike > svg"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).perform();
//		}
//		{
//			WebElement element = driver.findElement(By.tagName("body"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element, 0, 0).perform();
//		}
//		{
//			WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//			js.executeScript(
//					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Knowledge Source Data</p>'}",
//					element);
//		}
		driver.findElement(By.xpath("//*[@id=\"knowledgeSourceName\"]/quill-editor/div[2]/div[1]/p")).sendKeys("Knowledge Source Data");
		
//		driver.findElement(By.cssSelector(".ql-blank > p")).click();
//		{
//			WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//			js.executeScript(
//					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>knowledge description</p>'}",
//					element);
//		}
		driver.findElement(By.xpath("//*[@id=\"knowledgeSourceDescription\"]/quill-editor/div[2]/div[1]/p")).sendKeys("knowledge description");
		
		driver.findElement(By.id("knowledgeSourceUrl")).click();
		driver.findElement(By.id("knowledgeSourceUrl")).sendKeys("google.com");
		driver.findElement(By.id("knowledgeSourceType")).click();
//		{
//			WebElement dropdown = driver.findElement(By.id("knowledgeSourceType"));
//			dropdown.findElement(By.xpath("//option[. = 'Policy']")).click();
//		}
		Select dropdownType = new Select(driver.findElement(By.id("knowledgeSourceType")));
	    dropdownType.selectByValue("POLICY");
	    
		//driver.findElement(By.cssSelector(".cdk-focused rect")).click();
//		driver.findElement(By.id("nb-option-1")).click();
//		{
//			WebElement element = driver
//					.findElement(By.cssSelector("#knowledgeSourceDescription .ql-list:nth-child(5)"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element).perform();
//		}
//		{
//			WebElement element = driver.findElement(By.tagName("body"));
//			Actions builder = new Actions(driver);
//			builder.moveToElement(element, 0, 0).perform();
//		}
	    
	    driver.findElement(By.xpath("//button[normalize-space()='Select Project']")).click();
		{
			WebElement dropdown = driver.findElement(By.xpath("//button[normalize-space()='Select Project']"));
			dropdown.findElement(By.xpath("//nb-option[contains(text(),'root')]")).click();
		}

		driver.findElement(By.xpath("//button[normalize-space()='Select Folder']")).click();
		{
			WebElement dropdown = driver.findElement(By.xpath("//button[normalize-space()='Select Folder']"));
			dropdown.findElement(By.xpath("//nb-option[contains(text(),'untag')]")).click();
		}
		driver.findElement(By.xpath("//button[normalize-space()='Add Knowledge Source']")).click();
//		driver.findElement(By.cssSelector(".placeholder")).click();
//		driver.findElement(By.id("nb-option-345")).click();
//		driver.findElement(By.cssSelector(".btn-block")).click();
//		driver.findElement(By.cssSelector(".mb-3 .form-control")).click();
//		driver.findElement(By.cssSelector(".ng-dirty")).sendKeys("knowledge Source Data");
//		driver.findElement(By.cssSelector(".mb-3 .btn")).click();
//		driver.findElement(By.cssSelector(".item-name:nth-child(3)")).click();
//		driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
		
		Thread.sleep(5000);
		driver.findElement(By.xpath("/html/body/dfm-root/dfm-main-container/nb-layout/div[1]/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[1]/dfm-home-container/nb-card/div/div[1]/dfm-search-control/div/div[1]/input")).sendKeys("knowledge Source Data");
		Thread.sleep(4000);
		driver.findElement(By.xpath("/html/body/dfm-root/dfm-main-container/nb-layout/div[1]/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[1]/dfm-home-container/nb-card/div/div[1]/dfm-search-control/div/div[1]/div/i")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/dfm-root/dfm-main-container/nb-layout/div[1]/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[2]/dfm-search-container/nb-card/div/div[2]/div[2]/dfm-infinite-search-list/nb-list/nb-list-item/dfm-preview-container/div/dfm-search-list-item/div/div/span/span[2]")).click();
		Thread.sleep(5000);
//		{
//			WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//			js.executeScript(
//					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Hello Prefix</p>'}",
//					element);
//		}
		driver.findElement(By.xpath("//*[@id=\"knowledgeSourcePrefix\"]/quill-editor/div[2]/div[1]/p")).sendKeys("Hello Prefix");
		Thread.sleep(4000);
		
//		driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
//		{
//			WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//			js.executeScript(
//					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Knowledge Source Data Updated</p>'}",
//					element);
//		}
		
		driver.findElement(By.xpath("//*[@id=\"knowledgeSourceName\"]/quill-editor/div[2]/div[1]/p")).sendKeys(" Updated");
		Thread.sleep(4000);
		
//		driver.findElement(By.cssSelector(".rich-text-editor-focus p")).click();
//		{
//			WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//			js.executeScript(
//					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>knowledge description Updated</p>'}",
//					element);
//		}
		
		driver.findElement(By.xpath("//*[@id=\"knowledgeSourceDescription\"]/quill-editor/div[2]/div[1]/p")).sendKeys(" Updated");
		Thread.sleep(4000);
		
		driver.findElement(By.cssSelector(".internal-expand-collapse-icon:nth-child(1)")).click();
		vars.put("window_handles", driver.getWindowHandles());
		driver.findElement(By.cssSelector(".btn-url")).click();
		vars.put("win9757", waitForWindow(2000));
		vars.put("root", driver.getWindowHandle());
		driver.switchTo().window(vars.get("win9757").toString());
		driver.close();
		driver.switchTo().window(vars.get("root").toString());
		driver.findElement(By.id("complexity")).click();
		driver.findElement(By.id("complexity")).sendKeys("complexity");
		driver.findElement(By.cssSelector("dfm-relation-objects-display:nth-child(1) .form-control")).click();
		js.executeScript("window.scrollTo(0,0)");
		
		//driver.findElement(By.id("item-16f64145-5b64-4d5f-abe5-351f7d477394")).click();
//		driver.findElement(By.xpath("//input[@class='form-control search-control ng-pristine ng-valid ng-touched']")).click();
//		Thread.sleep(3000);
//		driver.findElement(By.xpath("//*[@id=\"item-16f64145-5b64-4d5f-abe5-351f7d477394\"]")).click();
		
		driver.findElement(By.cssSelector(".add-object")).click();
		driver.findElement(By.xpath("//*[@id=\"name\"]/quill-editor/div[2]/div[1]/p")).sendKeys("Enter Organization");
		driver.findElement(By.xpath("//*[@id=\"description\"]/quill-editor/div[2]/div[1]/p")).sendKeys("Organization description");
	    driver.findElement(By.cssSelector(".form-group > #type")).click();
	    driver.findElement(By.cssSelector(".form-group > #type")).click();
	    driver.findElement(By.cssSelector(".form-group > #url")).click();
	    driver.findElement(By.cssSelector(".form-group > #url")).sendKeys("google.com");
	    driver.findElement(By.cssSelector(".btn-block")).click();
		
//		driver.findElement(By.cssSelector(".ng-star-inserted > .header-block > .eva-plus-circle-outline")).click();
//		driver.findElement(By.cssSelector(".ql-blank > p")).click();
//		{
//			WebElement element = driver.findElement(By.cssSelector(".rich-text-editor-focus > .ql-editor"));
//			js.executeScript(
//					"if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>Enter Coments</p>'}",
//					element);
//		}
//		driver.findElement(By.cssSelector(".mt-2")).click();
	    
	    Thread.sleep(15000);
	    
	    driver.findElement(By.xpath("/html/body/dfm-root/dfm-main-container/nb-layout/div[1]/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[3]/dfm-edit-knowledge-source-container/nb-card/div/div[2]/div[3]/div[1]/i[1]")).click();
	    driver.findElement(By.xpath("//*[@id=\"comment\"]/quill-editor/div[2]/div[1]/p")).sendKeys("Enter Comments");
	    driver.findElement(By.xpath("//button[normalize-space()='Send']")).click();
	    
	}
	
	 @Test (priority = 2)
	  public void verifyKnowledgeSourceDataDetails() throws InterruptedException {
		  
			Thread.sleep(5000);
			// close the open tab
			driver.findElement(By.xpath("//*[@id=\"tab-container\"]/li[3]/div/i")).click();
			Thread.sleep(2000);
			driver.findElement(By.xpath(
					"/html/body/dfm-root/dfm-main-container/nb-layout/div[1]/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[2]/dfm-search-container/nb-card/div/div[2]/div[1]/dfm-search-control/div/div[1]/input"))
					.clear();
			driver.findElement(By.xpath(
					"/html/body/dfm-root/dfm-main-container/nb-layout/div[1]/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[2]/dfm-search-container/nb-card/div/div[2]/div[1]/dfm-search-control/div/div[1]/input"))
					.sendKeys("Knowledge Source Data Updated");
			Thread.sleep(4000);
			driver.findElement(By.xpath(
					"/html/body/dfm-root/dfm-main-container/nb-layout/div/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[2]/dfm-search-container/nb-card/div/div[2]/div[2]/dfm-infinite-search-list/nb-list/nb-list-item/dfm-preview-container/div/dfm-search-list-item/div/div/span/span[2]"))
					.click();
			Thread.sleep(2000);
	  }
	 
	 @Test(priority = 3)
		public void validateKnowledgeSourceDataDetails() throws InterruptedException {

			String verifyPrefix = driver
					.findElement(By.xpath("//*[@id=\"knowledgeSourcePrefix\"]/quill-editor/div[2]/div[1]/p")).getText();
			System.out.println(verifyPrefix);
			Thread.sleep(1000);
			
			String verifyName = driver
					.findElement(By.xpath("//*[@id=\"knowledgeSourceName\"]/quill-editor/div[2]/div[1]")).getText();
			System.out.println(verifyName);
			Thread.sleep(1000);
			
			String verifyDescription = driver
					.findElement(By.xpath("//*[@id=\"knowledgeSourceDescription\"]/quill-editor/div[2]/div[1]")).getText();
			System.out.println(verifyDescription);
			Thread.sleep(1000);
			
			
			driver.findElement(By.cssSelector(".internal-expand-collapse-icon:nth-child(1)")).click();
			Thread.sleep(1000);
			
			String verifyComplexity = driver
					.findElement(By.xpath("//*[@id=\"complexity\"]")).getText();
			System.out.println(verifyComplexity);
			Thread.sleep(1000);
			
			driver.findElement(By.xpath("/html/body/dfm-root/dfm-main-container/nb-layout/div/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[3]/dfm-edit-knowledge-source-container/nb-card/div/div[2]/div[3]/div[1]/i[1]")).click();
			
			String verifyComments = driver
					.findElement(By.xpath("/html/body/dfm-root/dfm-main-container/nb-layout/div/div/div/div/div/nb-layout-column/dfm-tabs-container/div/div/div[3]/dfm-edit-knowledge-source-container/nb-card/div/div[2]/div[3]/div[2]/dfm-comments-container/div/dfm-comment-item-display/div/div[2]/div[2]")).getText();
			System.out.println(verifyComments);
			Thread.sleep(1000);
			
	  }
}
